# Generated by Django 6.0.2 on 2026-03-17 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='notes.note'),
        ),
    ]
